version: '3'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_apigateway
    ports:
      - '6500:5432'
    volumes:
      - progresDB:/var/lib/postgresql/data2
    env_file:
      - ./.env

  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq_apigateway
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq

    env_file:
      - ./.env
    networks:
      - rabbitmq_go_net

  redis:
    image: redis:alpine
    container_name: redis_apigateway
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
volumes:
  progresDB:
  redisDB:

networks:
  rabbitmq_go_net:
    driver: bridge
